### ISSUE TITLE
out_of_range error

### ISSUE THREAD

**Issue by ghost** [david-juan/ChromDet#3]
Hi,
I am running an analysis on 5 samples (ChromHMM output, 4-column BED files, "chr" prefixed chromosome names), which terminates as follows:
```bash
terminate called after throwing an instance of 'std::out_of_range'
what():  vector::_M_range_check
Aborted (core dumped)
```
As far as I can tell, the files generated by the prep script look normal. Any ideas what to look for?
Best,
Peter

**Comment by david-juan** [comment]
Hi @mpi-pebert 

Could you specify in which step it terminates?
Is this happening in the preparation or in the S3det analysis step?

Best,

David

**Comment by ghost** [comment]
Hi @david-juan ,
I repeated the analysis saving the log file; turns out that ChromDet is considering all 5 samples as outliers and removes all of them:
```
Initial number of sequences: 5
    Initial number of sequences: 5
    Initial number of positions: 547505
    Number of outliers: 5
    OUTLIER REMOVED: sample_1
    OUTLIER REMOVED: sample_2
    OUTLIER REMOVED: sample_3
    OUTLIER REMOVED: sample_4
    OUTLIER REMOVED: sample_5
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check
    Final number of positions after removing gappy columns: 547505
Aborted (core dumped)
```
While this is the obvious cause of the error (though, terminating with a core dump is not so nice...), I find it a bit strange that 5 out of 5 samples can be outliers, given that they passed QC. Any thoughts on that? Otherwise, I guess this issue could be closed.
Best,
Peter

**Comment by david-juan** [comment]
Hi @mpi-pebert ,

First of all, I must say that, probably, five are too few samples for the kind of analysis performed by ChromDet (MCA + clustering + CDRs detection). 

In ChromDet, we define outliers based on a minimal percentage of identity (40% by default) among the different samples. Your output implies that none of your five samples have more than 40% of its regions in the same state than any other of the samples in your input file. In our experience, this is an uncommon scenario when comparing chromatin states segmentations from healthy samples.

In fact, I would say that it is very unlikely to get useful information from such highly divergent samples (even if most of the samples are so divergent) because of the lack of internal data structure required for a meaningful clustering. So, first, I would wonder whether you really want to do this analysis.

In any case, I have modified the scripts so that you can decide your own threshold. For this, you should update your ChromDet installation, as I have also fixed other minor bugs and renamed some files in a more consistent way. With this installation you will be able to modify the identity threshold at any of the following steps (don't forget the quotes as you are providing a string with S3det options):

a) Running the full pipeline (using -f option in run_S3det_analysis.pl):
     ./run_S3det_analysis.pl -d <dir containing the bedfiles> -c <file with the equivalences between chromatin states and their collapse> -a <file with human meaningful names for the samples> -s <path to the directory containining S3det> -v -f "-s <custom percentage of identity>"

b) Running ChromDet from the already pre-processed fasta files (using -c option in S3det_interface.pl).
    ./S3det_interface.pl -d <dir containing the fasta file> -f <fasta file generated by prepare_S3det_analysis.pl> -x <tab file generated by prepare_S3det_analysis.pl> -s <path to S3det binary file> -c "-v -s <custom percentage of identity>"

I hope this will help,
 
Best,

David

**Comment by ghost** [comment]
Hi @david-juan ,
thanks for your reply.
> this is an uncommon scenario when comparing chromatin states segmentations from healthy samples

Well, if you literally mean "healthy" as opposed to control samples, then this makes sense, the 5 samples were indeed disease samples. Thanks for sharing your experience on this.

I will update my installation of ChromDet and run it on the full dataset.
Apart from that, since this is not a bug in ChromDet, I am closing this issue now. Thanks a lot for your input.
Best,
Peter
