### ISSUE TITLE
advice on dataset

### ISSUE THREAD

**Issue by ptrebert** [david-juan/ChromDet#4]
Hi,
I am trying to run ChromDet on a comparably small dataset (4 cell types, 2/2/2/3 replicates). While the clustering seems to work (= produces output), the last step fails with the info that there is not enough group diversity to run the analysis. Can you give some empirical guidelines on how the dataset should be composed to be suitable for ChromDet? Or are there other ways to avoid this situation? Thanks for your help.
Best,
Peter

**Comment by david-juan** [comment]
Hi Peter,

The problem is not the dataset size, but the small number of replicates.
In our analyses we require a minimum number of 3 biological replicates per cell type.

In brief, the minimum reliable situation requires at least 3 biological replicates for at least 3 different cell types.
The ideal scenario would present from 5 to 10 replicates in four or more cell types.
With fewer replicates you can obtain a high number of false positives (regions that are not really conserved within the cell types).

As our protocol is blind to the actual number of replicates, we require that the number of samples in a detected group should be higher than 2.

While I would be very cautious about the interpretation of the results for smaller groups, you can retrieve their results for exploratory purposes by changing this minimum number of replicates per cell type.
For this, you need to invoque run_S3det_analysis.pl with the additional flag: -f “-m 2” (please keep the quotes).
-f allows to modify the parameters of S3det and -m fixes the minimum number of samples per group.
For a complete list of these paramaters, please look at the help for S3det by executing S3det_v2.4.exe in the S3Det_modified/ directory.

I hope this helps you.

Best

David

**Comment by ptrebert** [comment]
Hi David,
thanks a lot for this advice - I'll see what I can do with it.
Best,
Peter
